import os
import sys
import torch

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from image_generation.config import ImageModelConfig
from image_generation.model.vae import VAE
from image_generation.model.text_encoder import TextEncoder
from image_generation.model.diffusion import LatentDiffusion
from image_generation.scheduler import DDPMScheduler
import config as text_config
from tokenizer.bpe import BPETokenizer

class ModelBridge:
    def __init__(self, image_pipeline_config=None):
        self.image_config = image_pipeline_config or ImageModelConfig.load()
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.scheduler = DDPMScheduler()
        
        self.is_loaded = False
        self.vae = None
        self.text_encoder = None
        self.diffusion = None
        self.tokenizer = None
        
    def load_models_if_needed(self):
        if self.is_loaded:
            return True
            
        print("\n[Bridge] Waking up Generation Pipeline. Loading Models...")
        vae_path = os.path.join(self.image_config.output_dir_model, "vae_best.pt")
        diff_path = os.path.join(self.image_config.output_dir_model, "diffusion_best.pt")
        tok_path = os.path.join(text_config.tokenizer_dir, "tokenizer.json")
        
        if not os.path.exists(vae_path) or not os.path.exists(diff_path) or not os.path.exists(tok_path):
            print("[Bridge] ERROR: You must completely train Option 6 and Option 7 first! Models are missing.")
            return False
            
        self.tokenizer = BPETokenizer.load(tok_path)
        self.image_config.vocab_size = len(self.tokenizer.vocab) # Force sync parameter
            
        self.vae = VAE(latent_channels=self.image_config.vae_channels).to(self.device)
        self.vae.load_state_dict(torch.load(vae_path, map_location=self.device, weights_only=False)["model"])
        self.vae.eval()
        
        chk = torch.load(diff_path, map_location=self.device, weights_only=False)
        self.text_encoder = TextEncoder(self.image_config.vocab_size, self.image_config.text_embedding_dim, self.image_config.text_max_seq_len).to(self.device)
        self.text_encoder.load_state_dict(chk["text_encoder"])
        self.text_encoder.eval()
        
        self.diffusion = LatentDiffusion(in_channels=self.image_config.diffusion_channels, text_embed_dim=self.image_config.text_embedding_dim).to(self.device)
        self.diffusion.load_state_dict(chk["diffusion"])
        self.diffusion.eval()
        
        self.is_loaded = True
        return True
        
    def process_chat_message(self, message):
        """
        Intercepts chat messages generated by the Chatbot.
        """
        trigger = "/imagine "
        if trigger in message:
            start_idx = message.find(trigger) + len(trigger)
            prompt = message[start_idx:].strip()
            print(f"\n[Bridge] Starting iterative Image Generation for: '{prompt}'")
            
            if not self.load_models_if_needed():
                return {"type": "error", "content": "Models missing."}
                
            with torch.no_grad():
                # 1. Encode text context
                tokens = self.tokenizer.encode(prompt)
                if len(tokens) > self.image_config.text_max_seq_len:
                    tokens = tokens[:self.image_config.text_max_seq_len]
                else:
                    tokens = tokens + [0] * (self.image_config.text_max_seq_len - len(tokens))
                input_ids = torch.tensor([tokens], dtype=torch.long, device=self.device)
                context = self.text_encoder(input_ids)
                
                # 2. Setup pure noise
                latents = torch.randn((1, self.image_config.vae_channels, self.image_config.latent_height, self.image_config.latent_width), device=self.device)
                
                # 3. Denoiser loop (50 steps via DDIM)
                inference_steps = 50
                step_ratio = self.scheduler.num_train_timesteps // inference_steps
                
                print("[Bridge] Executing 50-Step DDIM Denoising Matrix...")
                times = [i * step_ratio for i in range(inference_steps)]
                times = list(reversed(times))
                
                for i, t in enumerate(times):
                    timesteps = torch.tensor([t], device=self.device).long()
                    
                    noise_pred = self.diffusion(latents, timesteps, context)
                    
                    prev_t = times[i + 1] if i < len(times) - 1 else -1
                    latents = self.scheduler.step_ddim(model_output=noise_pred, timestep=t, prev_timestep=prev_t, sample=latents)
                    
                # 4. Final VAE Decode
                print("[Bridge] Denoising Complete. Reconstructing via Factor-8 VAE...")
                image_tensor = self.vae.decode(latents)
                image_tensor = (image_tensor / 2 + 0.5).clamp(0, 1) # Normalize standard bounds mapping
                image_tensor = image_tensor.cpu().permute(0, 2, 3, 1).numpy()[0]
                
                from PIL import Image
                import numpy as np
                image_np = (image_tensor * 255).astype(np.uint8)
                img = Image.fromarray(image_np)
                
                if not os.path.exists(self.image_config.output_dir_image):
                    os.makedirs(self.image_config.output_dir_image, exist_ok=True)
                path = os.path.join(self.image_config.output_dir_image, "latest_generation.jpg")
                img.save(path)
                print(f"[Bridge] Real image sequence physically complete. Saved strictly to: {path}")
            
            return {
                "type": "image",
                "prompt": prompt,
                "status": "passed_to_image_model"
            }
        
        return {
            "type": "text",
            "content": message
        }
